### ISSUE TITLE
Raffle Bug - Could not make a new raffle ticket for a "Date with Preston"

### ISSUE THREAD

**Issue by ryanadanderson** [NullVoxPopuli/swing-dance-registration-system#101]
Raffle bug? I couldn't make a new ticket. 

![image](https://cloud.githubusercontent.com/assets/10438465/5654971/a8e488e0-9696-11e4-9312-3d92064db8a6.png)

![image](https://cloud.githubusercontent.com/assets/10438465/5654966/96031066-9696-11e4-8579-add6307879cc.png)

**Comment by NullVoxPopuli** [comment]
fixed :-)
