### ISSUE TITLE
Raffle Tickets - Should people be able to buy them online?

### ISSUE THREAD

**Issue by ryanadanderson** [NullVoxPopuli/swing-dance-registration-system#102]
I added the raffle ticket option and new registrants can't seem to purchase it. An admin can't add it to them either. (I think)

**Comment by NullVoxPopuli** [comment]
they can. did you make tickets? 
I increased the visibility of the new ticket button:

![screenshot from 2015-01-07 20 33 33](https://cloud.githubusercontent.com/assets/199018/5656554/87d464ac-96ac-11e4-93fa-edd02167649f.png)

**Comment by ryanadanderson** [comment]
I clicked "New Ticket" and Got this again. Are you referencing a file on your personal drive (or somewhere that you have access to) :-P

I should also note that this is my collaboration account, not the test@test.com account. 

Other than that, I don't know. 

![image](https://cloud.githubusercontent.com/assets/10438465/5656769/e0c0d192-96af-11e4-8b9f-812057697a95.png)

**Comment by NullVoxPopuli** [comment]
fixed
