### ISSUE TITLE
Really Big Check box (misleading title)

### ISSUE THREAD

**Issue by ryanadanderson** [NullVoxPopuli/swing-dance-registration-system#103]
![image](https://cloud.githubusercontent.com/assets/10438465/5655076/daf91db8-9697-11e4-8b28-f00a024a7d00.png)

**Comment by NullVoxPopuli** [comment]
done
![screenshot from 2015-01-07 20 28 55](https://cloud.githubusercontent.com/assets/199018/5656529/e912febe-96ab-11e4-8045-adae5237b881.png)

**Comment by NullVoxPopuli** [comment]
the check is a button for entering check numbers
