### ISSUE TITLE
Tiers should be able to increment based on number of users

### ISSUE THREAD

**Issue by NullVoxPopuli** [NullVoxPopuli/swing-dance-registration-system#104]
Numbers of users in a particular Package (number of full weekend)
Number of leads / number of follows
Number of pure total registrants

**Comment by ryanadanderson** [comment]
With that, maybe an updating chart that may be embedded on the events website?

Like here: http://www.pirateswing.com/register.phtml

**Comment by NullVoxPopuli** [comment]
good idea! :-)

**Comment by NullVoxPopuli** [comment]
done for total users
