### ISSUE TITLE
Issue upon clicking http://www.aeonvera.com/hosted_events/11/a_la_carte_orders

### ISSUE THREAD

**Issue by ryanadanderson** [NullVoxPopuli/swing-dance-registration-system#107]
I clicked on the link to the right on image 1 to go to image 2.

Image 1
![image](https://cloud.githubusercontent.com/assets/10438465/5655888/9f542306-96a2-11e4-8f2f-4f0af641be8b.png)

Image 2
![image](https://cloud.githubusercontent.com/assets/10438465/5655884/8629679c-96a2-11e4-8d4b-c7c8b18f6bc8.png)

**Comment by NullVoxPopuli** [comment]
fixed.
