### ISSUE TITLE
Edit Profile does not seem to be working.

### ISSUE THREAD

**Issue by ryanadanderson** [NullVoxPopuli/swing-dance-registration-system#108]
![image](https://cloud.githubusercontent.com/assets/10438465/5656331/a5a97c1e-96a8-11e4-83a4-66cc2a8da306.png)

![image](https://cloud.githubusercontent.com/assets/10438465/5656412/b4eb219a-96a9-11e4-8cfb-8c0b8c4a00b6.png)

**Comment by NullVoxPopuli** [comment]
fixed
