### ISSUE TITLE
At the door > A-la-carte > buttons popup issue

### ISSUE THREAD

**Issue by ryanadanderson** [NullVoxPopuli/swing-dance-registration-system#109]
http://www.aeonvera.com/hosted_events/11/dance_only/new

After clicking on a button and then hitting an "X" to close the popup, I cannot open the popup again. 

![image](https://cloud.githubusercontent.com/assets/10438465/5656616/c97a5a3c-96ad-11e4-8b8c-3ed070e85099.png)

**Comment by ryanadanderson** [comment]
It's the a-la-care button.

**Comment by NullVoxPopuli** [comment]
fixed
