### ISSUE TITLE
Add a Non-Binary gender for housing preference

### ISSUE THREAD

**Issue by ryanadanderson** [NullVoxPopuli/swing-dance-registration-system#111]
Some might feel most comfortable with this option.

**Comment by NullVoxPopuli** [comment]
Wouldn't "no preference' cover that?

**Comment by ryanadanderson** [comment]
"no preference" would be I'm comfortable with any gender while "non-binary" would prefer a person who doesn't identify within the male/female category. Maybe an "other preference" checkbox with an explanation text box. I'll ask around really quick and get back to ya.

**Comment by NullVoxPopuli** [comment]
Well, they aren't selecting what gender they are. They are selecting what gender they would like to stay with. 
Also, biologically, there are only two genders. So... I don't think I'm going to change it.
