### ISSUE TITLE
Big Red "Select a level" box houdini

### ISSUE THREAD

**Issue by ryanadanderson** [NullVoxPopuli/swing-dance-registration-system#113]
Big Red Swing Weekend
http://bigredswingweekend.aeonvera.com/register/new

The skills box disappears when I click the "Full Weekend Pass - $45" & Beginner Dance Track - $35" radio buttons before I'm able to select something. Does this skills box nee to be there in the first place?

![image](https://cloud.githubusercontent.com/assets/10438465/5679646/5e53db06-97d0-11e4-9160-1dc91165db4c.png)

![image](https://cloud.githubusercontent.com/assets/10438465/5679652/6c4b17d8-97d0-11e4-96e2-e5a07399ec41.png)

**Comment by NullVoxPopuli** [comment]
This was a configuration issue on big red's side of things.

Packages can 'require tracks' and none of the packages were configured to do so.
