### ISSUE TITLE
Find events

### ISSUE THREAD

**Issue by dovalojd** [NullVoxPopuli/swing-dance-registration-system#118]
Allow users to search or browse the events available on aeonvera.

**Comment by NullVoxPopuli** [comment]
I like the idea! currently there is only: aeonvera.com/home/calendar

**Comment by dovalojd** [comment]
Actually, I'm reasonably happy with the calendar (it'll probably need some more features once you have more events, but it's quite adequate for three events), I just didn't know that it already existed because I couldn't find any way to navigate to it.

**Comment by NullVoxPopuli** [comment]
yeah, I might put a link to it either in the main top navigation, or find a way to simplify the the tables and such on the home screen, and make a left-hand navigation and add it there.

**Comment by NullVoxPopuli** [comment]
I changed the home screen, and added a link to the events calendar. The events calendar is also now available without logging in. (Registering still requires logging in)
