### ISSUE TITLE
"I have pets" was selected as TRUE as does not show TRUE in INFORMATION sections

### ISSUE THREAD

**Issue by ryanadanderson** [NullVoxPopuli/swing-dance-registration-system#94]
Pets does NOT show show as TRUE in information section.
Pets does show as TRUE in housing section.

*******Not Correct*******
![image](https://cloud.githubusercontent.com/assets/10438465/5650216/678f543c-966a-11e4-9efa-5fbc84af2a08.png)

![image](https://cloud.githubusercontent.com/assets/10438465/5650230/8b16d740-966a-11e4-94cc-e71d3972fa2d.png)

*******Correct*******
![image](https://cloud.githubusercontent.com/assets/10438465/5650238/98ab1150-966a-11e4-9244-de7b2f7c625d.png)

**Comment by ryanadanderson** [comment]
Another shot with URL included (I don't know how you work your magic.)

![image](https://cloud.githubusercontent.com/assets/10438465/5651368/d43de76a-9674-11e4-80b6-271c57334c49.png)

**Comment by ryanadanderson** [comment]
Just checked again. Still not working :-P I clicked true for smoking and it showed like this.

![image](https://cloud.githubusercontent.com/assets/10438465/5656727/25265218-96af-11e4-9513-bb971ce126ce.png)

**Comment by ryanadanderson** [comment]
Also, on the above picture, I clicked "I can transport people" and it didn't carry over as true.

**Comment by NullVoxPopuli** [comment]
I think the registration summary page is resolved. I'll need to run through the registration process to be sure

**Comment by NullVoxPopuli** [comment]
This is resolved.
