### ISSUE TITLE
Dance orrientation did not carry over to .csv

### ISSUE THREAD

**Issue by ryanadanderson** [NullVoxPopuli/swing-dance-registration-system#97]
![image](https://cloud.githubusercontent.com/assets/10438465/5650842/0df55394-9670-11e4-8dcd-5c48dc9ce8f8.png)

**Comment by NullVoxPopuli** [comment]
This needs to be part of the adding separate dance orientation to competitions

**Comment by NullVoxPopuli** [comment]
fixed
