### ISSUE TITLE
Something went wrong when trying to add an a-la-cart item

### ISSUE THREAD

**Issue by ryanadanderson** [NullVoxPopuli/swing-dance-registration-system#99]
I think it was an a-la-cart item

![image](https://cloud.githubusercontent.com/assets/10438465/5650931/eda2f9ba-9670-11e4-84b5-ffe585d621fa.png)

**Comment by NullVoxPopuli** [comment]
can you also post that picture?

**Comment by ryanadanderson** [comment]
Already on it :-)

![image](https://cloud.githubusercontent.com/assets/10438465/5650949/2c62c5a4-9671-11e4-9126-2af979e98bd6.png)

**Comment by ryanadanderson** [comment]
I think it was due to the date. Was the expiration date before the event?

**Comment by NullVoxPopuli** [comment]
I have not been able to replicate. 
maybe it was fixed with some related update?
